/// Flutter icons Iaso
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Iaso
///      fonts:
///       - asset: fonts/Iaso.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Iaso {
  Iaso._();

  static const _kFontFam = 'Iaso';

  static const IconData burnout = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData sore_throat = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData headache = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData pain = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData fever = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData sweat = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData cough = IconData(0xe806, fontFamily: _kFontFam);
}
